const PDFDocument = require('pdfkit');

const generateResultPDF = (result, res) => {
  const doc = new PDFDocument();

  // Set response headers to trigger download
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=result_${result.date}.pdf`);

  doc.pipe(res);

  // PDF Content
  doc.fontSize(25).text('DEAR LOTTERY RESULT', { align: 'center' });
  doc.moveDown();
  doc.fontSize(18).text(`Draw Name: ${result.drawName}`);
  doc.fontSize(14).text(`Date: ${result.date}`);
  doc.text(`Time: ${result.drawTime}`);
  doc.moveDown();

  doc.fontSize(16).text('Winning Numbers:', { underline: true });
  doc.moveDown(0.5);

  Object.entries(result.winningNumbers).forEach(([prize, numbers]) => {
    doc.fontSize(14).fillColor('blue').text(`${prize}:`, { continued: true });
    doc.fillColor('black').text(` ${numbers.join(', ')}`);
    doc.moveDown(0.5);
  });

  doc.moveDown();
  doc.fontSize(10).fillColor('grey').text('Generated by DEAR LOTTERY App', { align: 'center' });

  doc.end();
};

module.exports = { generateResultPDF };
